# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-28 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='dob',
            field=models.DateField(max_length=100),
        ),
    ]
