# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0002_adminmodel_amount'),
        ('hotelmanagement', '0002_auto_20180928_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requeststatus', models.CharField(default='pending', max_length=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteladmin.AdminModel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.UserRegistration')),
            ],
        ),
    ]
