# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-29 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
